### PR TITLE
Removed the author's name

### PR DESCRIPTION
**Pull request by aadityaagrawal**
Removed the author's name from the multiple files.

### CODE REVIEW

**Comment by Meldiron** [comment]
Linking issue: https://github.com/appwrite/appwrite/issues/4397

**Review by Meldiron — CHANGES_REQUESTED** [review]
One tiny comment 🤏 I can mark as approved once resolved.

**Comment by Meldiron** [comment]
@aadityaagrawal Let's please apply this to all your changes - in all places where you removed the author line, let's remove the whole code block.

**Review by Meldiron — APPROVED** [review]
Looks great 🎉

**Comment by christyjacob4** [comment]
@aadityaagrawal please resolve the conflicts

**Pull request closed without merging**
